### ISSUE TITLE
Feedbacks landing pages

### ISSUE THREAD

**Issue by guiguiwagon** [homepaycompany/landing_pages#8]

**Comment by guiguiwagon** [comment]
@Aporcheron 
<img width="1246" alt="zenkey" src="https://user-images.githubusercontent.com/26580651/37978009-4ab77b18-31e5-11e8-8662-ddf4e807f4ad.png">
<img width="1164" alt="zenkey" src="https://user-images.githubusercontent.com/26580651/37978073-704f91da-31e5-11e8-8f6f-c296372b4ece.png">

**Comment by oruhtra** [comment]
Après lecture des différentes pages du site je trouve qu'on explique jamais clairement qu'on a à la fois une activité d'agence et de courtier et que c'est justement ce qui nous permet d'offrir des services à 0€ sur l'agence. On le mentionne sur la landing dans une boite, mais du coups comme ce n'est pas vraiment mis en avant je trouve que ça trouble complètement la perception du service. Par ailleurs comme c'est quelque chose de nouveau il faut sand doute rassurer le vendeur dessus (on est impartial, on va favoriser les meilleurs offres, on ne va pas chercher à vendre vite au prix le plus faible juste pour obtenir le + de prêts etc.) => sans doute que la page Services & Prix es tel bon endroit pour le faire
